#!/usr/bin/env bash

set -o pipefail

MAILCOW_CONFIG_FILE=/opt/mailcow-dockerized/mailcow.conf
OUTPUT_FILE=./conf/settings.ini

[ ! -f $MAILCOW_CONFIG_FILE ] && echo "Mailcow config not found. " && exit 1
source $MAILCOW_CONFIG_FILE

# BEGIN SCRIPT
echo "# Autogenerated getmail config on $(date)" > "$OUTPUT_FILE"
echo "[DEFAULT]" >> "$OUTPUT_FILE"
echo "imap_debug:        False" >> "$OUTPUT_FILE"
echo "imap_move_enable:  False" >> "$OUTPUT_FILE"
echo "imap_move_folder:  getmail" >> "$OUTPUT_FILE"
echo "imap_sync_folder:  INBOX" >> "$OUTPUT_FILE"
echo "lmtp_hostname:     dovecot-mailcow" >> "$OUTPUT_FILE"
echo "lmtp_port:         24" >> "$OUTPUT_FILE"
echo "lmtp_debug:        False" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

docker compose --project-directory ../mailcow-dockerized exec mysql-mailcow mysql -u "$DBUSER" -p"$DBPASS" "$DBNAME" -B -N -e "
SELECT CONCAT_WS(CHAR(10),
  CONCAT('[JOB_' ,user2 ,'_' ,id ,']'),
  CONCAT('imap_hostname: ', host1), 
  CONCAT('imap_port: ', port1), 
  CONCAT('imap_ssl: ', IF(port1 = 993, 'True', 'False')), 
  CONCAT('imap_username: ', user1), 
  CONCAT('imap_password: ', password1), 
  CONCAT('lmtp_recipient: ', user2), 
  ''
)
FROM imapsync
WHERE active = 0;
" | sed 's/\\n/\n/g' >> "$OUTPUT_FILE"
